### ISSUE TITLE
remote VNC unusable on iPhone SE

### ISSUE THREAD

**Issue by vegadka** [victronenergy/apps_vrm_ios#1]
If you use the remote feature to access the CCGX (BBB) remote interface, you will have no chance to hit the settings button since the lower statusbar is half in front of it.

**Comment by mpvader** [comment]
Hi @vegadka  thanks. Could you post a screenshot? 

And this is when accessing Remote Console on VRM, right? Not on LAN I mean.
And browsing the VRM Portal inside the VRM app.

Also, please try going to he VRM portal (https://vrm.victronenergy.com) on Safari directly. And then opening the Remote Console. So not via the app. Does that go better?

**Comment by vegadka** [comment]
Yes. through the browser in the app. In the PCs browser everything is fine. It#s just unclickable since the screen of the SE ( same as 5/5S ) is to small.



Thanks
Daniel

**Comment by mpvader** [comment]
Hi @vegadka, we've submitted a new version of the iOS version of the VRM app that fixes this. Version 2.3. You'll see it soon on your phone. Matthijs
